"""
tora_monte_carlo_simulation.py

This script implements the temporal dynamics simulation and the Monte Carlo 
robustness evaluation for the Task-Oriented Rank Adaptation (TORA) framework.
It tracks the topological shifts as new tasks arrive and assesses the probability 
of Shielding vs. Boosting across 100,000 random sequences.
"""

import pandas as pd
import numpy as np
import random

# ==============================================================================
# GENERAL CONFIGURATIONS & DATA LOADING
# ==============================================================================
# Matrix generated by the structural affinity router
AFFINITY_MATRIX_PATH = r"C:\Users\reisy\OneDrive\Documentos\TORA\structural_affinity_matrix.csv"

# TOPOLOGICAL HYPERPARAMETERS (Derived from empirical validation)
K_NEIGHBORS = 3
ROUTING_THRESHOLD = 84.5  # \bar{\theta}_3 threshold

print(f"Initiating TORA Topological Routing Simulation (k={K_NEIGHBORS}, threshold={ROUTING_THRESHOLD}°)...")
df_rank = pd.read_csv(AFFINITY_MATRIX_PATH)

structural_affinities = {}
for _, row in df_rank.iterrows():
    # Adjusted to match the column names from the previous script
    target = str(row['Incoming_Task']).lower()
    for i in range(1, 15):
        exp_col = f"Rank_{i}_Expert"
        sim_col = f"Rank_{i}_CosineSim"
        if exp_col in row and pd.notna(row[exp_col]):
            expert = str(row[exp_col]).lower()
            cosine_sim = float(row[sim_col])
            structural_affinities[(target, expert)] = cosine_sim

# DistilBERT Evaluation Benchmarks (15 Text Classification Tasks)
base_tasks = [
    'agnews', 'sst2', 'amazon', 'yelp', 'imdb', 'boolq', 
    'cb', 'copa', 'dbpedia', 'mnli', 'multirc', 'qqp', 
    'rte', 'wic', 'yahoo'
]

# ==============================================================================
# PHASE 1: SEQUENTIAL ROUTING AND TOPOLOGICAL SHIFT TRACKING
# ==============================================================================
print("\n[1/2] Executing Baseline Sequential Simulation (Generating Logs 01 and 02)...")

expert_memory_pool = []
routing_log = []
topological_shifts_log = []

top_k_state = {}

for step, incoming_task in enumerate(base_tasks, 1):
    
    # 1A. ROUTING DECISION (Boosting vs. Shielding)
    if len(expert_memory_pool) == 0:
        routing_log.append({
            'Step': step, 'Incoming_Task': incoming_task.upper(), 'Neighbors_Evaluated': 0,
            'Top_1_Expert': 'N/A', 'Mean_Angular_Distance': 'N/A', 'Decision': 'SHIELDING (Cold Start)'
        })
    else:
        router_candidates = []
        for expert in expert_memory_pool:
            if (incoming_task, expert) in structural_affinities:
                cos = structural_affinities[(incoming_task, expert)]
                ang = np.degrees(np.arccos(max(min(cos, 1.0), -1.0)))
                router_candidates.append({'expert': expert, 'angle': ang})
        
        # Sort in ascending order of angular distance \theta_i
        router_candidates = sorted(router_candidates, key=lambda x: x['angle'])
        
        top_k_router = router_candidates[:K_NEIGHBORS]
        top_1 = top_k_router[0]
        mean_theta = np.mean([c['angle'] for c in top_k_router])
        
        # Routing decision based on the geometric threshold
        if mean_theta < ROUTING_THRESHOLD:
            decision = f"BOOSTING ({top_1['expert'].upper()})"
        else:
            decision = f"SHIELDING (>={ROUTING_THRESHOLD}°)"
            
        routing_log.append({
            'Step': step, 'Incoming_Task': incoming_task.upper(), 'Neighbors_Evaluated': len(top_k_router),
            'Top_1_Expert': top_1['expert'].upper(), 'Mean_Angular_Distance': f"{round(mean_theta, 2)}°", 'Decision': decision
        })
    
    expert_memory_pool.append(incoming_task)

    # 1B. TOPOLOGICAL SHIFT AND DENSITY TRACKING
    for target_task in expert_memory_pool:
        network_candidates = []
        for neighbor in expert_memory_pool:
            if target_task != neighbor and (target_task, neighbor) in structural_affinities:
                cos = structural_affinities[(target_task, neighbor)]
                ang = np.degrees(np.arccos(max(min(cos, 1.0), -1.0)))
                network_candidates.append((neighbor, ang))
        
        network_candidates.sort(key=lambda x: x[1])
        
        new_top = network_candidates[:K_NEIGHBORS]
        new_top_names = [c[0].upper() for c in new_top]
        new_mean = np.mean([c[1] for c in new_top]) if new_top else 0.0
        
        if target_task in top_k_state:
            previous_state = top_k_state[target_task]
            previous_top_names = previous_state['names']
            previous_mean = previous_state['mean']
            
            if new_top_names != previous_top_names:
                if previous_top_names:
                    delta = new_mean - previous_mean
                    delta_text = f"{round(delta, 2)}°"
                    observation = "Topological Improvement" if delta < 0 else "Neighborhood Rearrangement"
                else:
                    delta_text = "N/A"
                    observation = "Initial Memory Population"

                topological_shifts_log.append({
                    'Step': step, 'Triggering_Task': incoming_task.upper(), 'Affected_Task': target_task.upper(),
                    'Previous_Top_K': " -> ".join(previous_top_names) if previous_top_names else "Empty",
                    'New_Top_K': " -> ".join(new_top_names),
                    'Previous_Mean': f"{round(previous_mean, 2)}°" if previous_top_names else "N/A",
                    'New_Mean': f"{round(new_mean, 2)}°",
                    'Angular_Delta': delta_text,
                    'Observation': observation
                })
        
        top_k_state[target_task] = {'names': new_top_names, 'mean': new_mean}

df_routing = pd.DataFrame(routing_log)
df_shifts = pd.DataFrame(topological_shifts_log)
df_routing.to_csv("01_routing_decisions.csv", index=False, encoding='utf-8-sig')
df_shifts.to_csv("02_topological_shifts.csv", index=False, encoding='utf-8-sig')

# ==============================================================================
# PHASE 2: MONTE CARLO SIMULATION (100,000 RANDOM SEQUENCES)
# ==============================================================================
NUM_SIMULATIONS = 100000
print(f"\n[2/2] Executing Monte Carlo Simulation ({NUM_SIMULATIONS} iterations for log 03)...")

task_statistics = {task: {'Boosting': 0, 'Shielding': 0} for task in base_tasks}

for sim in range(NUM_SIMULATIONS):
    random_sequence = base_tasks.copy()
    random.shuffle(random_sequence)
    mc_memory = []
    
    for mc_task in random_sequence:
        if len(mc_memory) == 0:
            task_statistics[mc_task]['Shielding'] += 1
        else:
            mc_candidates = []
            for exp in mc_memory:
                if (mc_task, exp) in structural_affinities:
                    cos = structural_affinities[(mc_task, exp)]
                    ang = np.degrees(np.arccos(max(min(cos, 1.0), -1.0)))
                    mc_candidates.append(ang)
            
            mc_candidates.sort()
            
            mc_mean = np.mean(mc_candidates[:K_NEIGHBORS])
            
            if mc_mean < ROUTING_THRESHOLD:
                task_statistics[mc_task]['Boosting'] += 1
            else:
                task_statistics[mc_task]['Shielding'] += 1
                
        mc_memory.append(mc_task)

mc_results = []
for task, counts in task_statistics.items():
    total_occurrences = counts['Boosting'] + counts['Shielding']
    percentage = (counts['Boosting'] / total_occurrences) * 100
    mc_results.append({
        'Task': task.upper(),
        'Boosting_Count': counts['Boosting'],
        'Shielding_Count': counts['Shielding'],
        'Transfer_Probability': f"{round(percentage, 1)}%"
    })

df_mc_summary = pd.DataFrame(mc_results).sort_values(by='Transfer_Probability', ascending=False)
df_mc_summary.to_csv("03_monte_carlo_robustness.csv", index=False, encoding='utf-8-sig')

print("\n Simulation complete! Log 03 now contains task sequence robustness and topological probabilities.")